fix(SkinManageDialog): add missing QMenu include
launcher/ui/dialogs/skins/SkinManageDialog.cpp: In member function ‘void SkinManageDialog::show_context_menu(const QPoint&)’:
launcher/ui/dialogs/skins/SkinManageDialog.cpp:344:18: error: variable ‘QMenu myMenu’ has initializer but incomplete type
  344 |     QMenu myMenu(tr("Context menu"), this);
      |                  ^~

Include appears to have been dropped transitively in either
8f2a4329e1dc2a2ccf7ac68f67de2547b3afd225 or 391113f5a340b006bb54a5016b7fbf8bcb17be40

Signed-off-by: Alfred Wingate <parona@protonmail.com>